#!/usr/bin/env node
/**
 * Claude Code Context Management Hook
 *
 * This hook helps manage session context by:
 * 1. Creating session summaries for long-running tasks
 * 2. Saving important findings to memory files
 * 3. Integrating with the memory MCP server
 *
 * Usage:
 * - Can be triggered via Notification hook for periodic context anchoring
 * - Can be called manually: node .claude/hooks/compress-context.js --save "summary text"
 *
 * Exit codes:
 * - 0: Success
 * - 1: Error
 */

const fs = require('fs');
const path = require('path');

// Configuration
const MEMORY_DIR = path.join(__dirname, '..', 'memory');
const SESSION_SUMMARY_FILE = path.join(MEMORY_DIR, 'session-summary.md');
const MAX_SUMMARIES = 10; // Keep last 10 session summaries

/**
 * Ensure memory directory exists
 */
function ensureMemoryDir() {
    if (!fs.existsSync(MEMORY_DIR)) {
        fs.mkdirSync(MEMORY_DIR, { recursive: true });
    }
}

/**
 * Get current timestamp in ISO format
 */
function getTimestamp() {
    return new Date().toISOString();
}

/**
 * Save a context anchor/summary
 */
function saveContextAnchor(summary, metadata = {}) {
    ensureMemoryDir();

    const anchor = {
        timestamp: getTimestamp(),
        summary: summary,
        metadata: {
            workingDirectory: process.cwd(),
            gitBranch: getGitBranch(),
            ...metadata
        }
    };

    // Append to session summary file
    const entry = `
## Context Anchor - ${anchor.timestamp}

**Branch:** ${anchor.metadata.gitBranch || 'unknown'}
**Directory:** ${anchor.metadata.workingDirectory}

### Summary
${anchor.summary}

---
`;

    // Read existing content and manage size
    let existingContent = '';
    if (fs.existsSync(SESSION_SUMMARY_FILE)) {
        existingContent = fs.readFileSync(SESSION_SUMMARY_FILE, 'utf-8');
    } else {
        existingContent = `# Session Summaries

This file contains context anchors and session summaries for AI agent continuity.
Generated by compress-context.js hook.

---
`;
    }

    // Add new entry
    const newContent = existingContent + entry;

    // Trim if too many summaries (keep header + last N summaries)
    const summaries = newContent.split('## Context Anchor');
    if (summaries.length > MAX_SUMMARIES + 1) {
        const header = summaries[0];
        const recentSummaries = summaries.slice(-MAX_SUMMARIES);
        const trimmedContent = header + recentSummaries.map(s => '## Context Anchor' + s).join('');
        fs.writeFileSync(SESSION_SUMMARY_FILE, trimmedContent);
    } else {
        fs.writeFileSync(SESSION_SUMMARY_FILE, newContent);
    }

    return anchor;
}

/**
 * Get current git branch
 */
function getGitBranch() {
    try {
        const { execSync } = require('child_process');
        return execSync('git branch --show-current', { encoding: 'utf-8' }).trim();
    } catch {
        return null;
    }
}

/**
 * Load recent session summaries
 */
function loadRecentSummaries(count = 5) {
    if (!fs.existsSync(SESSION_SUMMARY_FILE)) {
        return [];
    }

    const content = fs.readFileSync(SESSION_SUMMARY_FILE, 'utf-8');
    const summaries = content.split('## Context Anchor').slice(1); // Skip header

    return summaries.slice(-count).map(s => {
        const lines = s.trim().split('\n');
        const timestampMatch = lines[0]?.match(/- (.+)/);
        return {
            timestamp: timestampMatch?.[1] || 'unknown',
            content: s.trim()
        };
    });
}

/**
 * Generate context anchor template
 */
function generateContextAnchorTemplate() {
    return `
=== CONTEXT ANCHOR ===
Current Task: [description]
Completed: [list completed items]
Remaining: [list pending items]
Key Findings: [important insights]
Blockers: [any blockers]
Next Action: [specific next step]
======================
`;
}

// CLI interface
const args = process.argv.slice(2);

if (args.includes('--help') || args.includes('-h')) {
    console.log(`
Context Compression Hook for Claude Code

Usage:
  node compress-context.js --save "summary text"     Save a context anchor
  node compress-context.js --load [count]            Load recent summaries
  node compress-context.js --template                Show context anchor template
  node compress-context.js --clear                   Clear all summaries

Environment:
  MEMORY_DIR: ${MEMORY_DIR}
  SESSION_FILE: ${SESSION_SUMMARY_FILE}
`);
    process.exit(0);
}

if (args.includes('--save')) {
    const summaryIndex = args.indexOf('--save') + 1;
    const summary = args[summaryIndex] || 'No summary provided';
    const anchor = saveContextAnchor(summary);
    console.log(JSON.stringify({ success: true, anchor }));
    process.exit(0);
}

if (args.includes('--load')) {
    const countIndex = args.indexOf('--load') + 1;
    const count = parseInt(args[countIndex]) || 5;
    const summaries = loadRecentSummaries(count);
    console.log(JSON.stringify({ success: true, summaries }));
    process.exit(0);
}

if (args.includes('--template')) {
    console.log(generateContextAnchorTemplate());
    process.exit(0);
}

if (args.includes('--clear')) {
    ensureMemoryDir();
    if (fs.existsSync(SESSION_SUMMARY_FILE)) {
        fs.unlinkSync(SESSION_SUMMARY_FILE);
        console.log(JSON.stringify({ success: true, message: 'Session summaries cleared' }));
    } else {
        console.log(JSON.stringify({ success: true, message: 'No summaries to clear' }));
    }
    process.exit(0);
}

// When run as hook (via stdin)
let stdin = '';
try {
    stdin = fs.readFileSync(0, 'utf-8');
    if (stdin) {
        const input = JSON.parse(stdin);
        // Hook mode - could be extended for specific events
        console.log(JSON.stringify({ received: true, input_type: typeof input }));
    }
} catch {
    // No stdin or invalid input
}

process.exit(0);
