id: pat-260113-0726-vrxsik
category: general
type: preference
trigger:
  keywords: ["type", "annotations", "functions"]
  file_patterns: []
  context: add type annotations to all functions
content:
  wrong:

  right:

  rationale: add type annotations to all functions
metadata:
  source: explicit-teaching
  confidence: 1
  first_seen: 2026-01-13
  last_confirmed: 2026-01-13
  occurrences: 4
  confirmations: 3
  conflicts: 0
  related_files: []
tags: ["general", "type", "annotations", "functions"]