id: pat-260113-0726-q5h8dt
category: frontend
type: preference
trigger:
  keywords: ["always", "semicolons", "typescript"]
  file_patterns: []
  context: always use semicolons in TypeScript
content:
  wrong:

  right: semicolons in TypeScript
  rationale: always use semicolons in TypeScript
metadata:
  source: explicit-teaching
  confidence: 1
  first_seen: 2026-01-13
  last_confirmed: 2026-01-13
  occurrences: 4
  confirmations: 3
  conflicts: 0
  related_files: []
tags: ["frontend", "always", "semicolons", "typescript"]