id: pat-260113-0726-8v0s3q
category: frontend
type: preference
trigger:
  keywords: ["naming", "classes"]
  file_patterns: []
  context: use BEM naming for CSS classes
content:
  wrong:

  right:

  rationale: use BEM naming for CSS classes
metadata:
  source: explicit-teaching
  confidence: 1
  first_seen: 2026-01-13
  last_confirmed: 2026-01-13
  occurrences: 4
  confirmations: 3
  conflicts: 0
  related_files: []
tags: ["frontend", "naming", "classes"]