"""Incremental graph update logic.

Detects changed files via git diff, re-parses only changed + impacted files,
and updates the graph accordingly. Also supports CLI invocation for hooks.
"""

from __future__ import annotations

import fnmatch
import hashlib
import logging
import os
import subprocess
import time
from pathlib import Path
from typing import Optional

from .graph import GraphStore
from .parser import CodeParser

logger = logging.getLogger(__name__)

# Default ignore patterns (in addition to .gitignore)
DEFAULT_IGNORE_PATTERNS = [
    ".code-graph/**",
    "node_modules/**",
    ".git/**",
    "__pycache__/**",
    "*.pyc",
    ".venv/**",
    "venv/**",
    "dist/**",
    "build/**",
    ".next/**",
    "target/**",
    "*.min.js",
    "*.min.css",
    "*.map",
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "*.db",
    "*.sqlite",
    "*.db-journal",
    "*.db-wal",
]


def find_repo_root(start: Path | None = None) -> Optional[Path]:
    """Walk up from start to find the nearest .git directory."""
    current = start or Path.cwd()
    while current != current.parent:
        if (current / ".git").exists():
            return current
        current = current.parent
    if (current / ".git").exists():
        return current
    return None


def find_project_root(start: Path | None = None) -> Path:
    """Find the project root: git repo root if available, otherwise cwd."""
    root = find_repo_root(start)
    if root:
        return root
    return start or Path.cwd()


def get_db_path(repo_root: Path) -> Path:
    """Determine the database path for a repository.

    Creates the ``.code-graph/`` directory and an inner ``.gitignore``
    (with ``*``) so generated files are never committed.  If a legacy
    ``.code-graph.db`` exists at the repo root the database is migrated
    into the new directory (WAL/SHM side-files are discarded).
    """
    crg_dir = repo_root / ".code-graph"
    new_db = crg_dir / "graph.db"

    # Ensure directory exists
    crg_dir.mkdir(exist_ok=True)

    # Auto-create .gitignore inside the directory (idempotent)
    inner_gitignore = crg_dir / ".gitignore"
    if not inner_gitignore.exists():
        inner_gitignore.write_text(
            "# Auto-generated by code-graph — do not commit database files.\n"
            "# The graph.db contains absolute paths and code structure metadata.\n"
            "*\n"
        )

    # Migrate legacy database if present
    legacy_db = repo_root / ".code-graph.db"
    if legacy_db.exists() and not new_db.exists():
        legacy_db.rename(new_db)
    # Discard stale WAL/SHM side-files from the old location
    for suffix in ("-wal", "-shm", "-journal"):
        side = repo_root / f".code-graph.db{suffix}"
        if side.exists():
            side.unlink()

    return new_db


def _load_ignore_patterns(repo_root: Path) -> list[str]:
    """Load ignore patterns from .code-graphignore file."""
    patterns = list(DEFAULT_IGNORE_PATTERNS)
    ignore_file = repo_root / ".code-graphignore"
    if ignore_file.exists():
        for line in ignore_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                patterns.append(line)
    return patterns


def _should_ignore(path: str, patterns: list[str]) -> bool:
    """Check if a path matches any ignore pattern."""
    return any(fnmatch.fnmatch(path, p) for p in patterns)


def _is_binary(path: Path) -> bool:
    """Quick heuristic: check if file appears to be binary."""
    try:
        chunk = path.read_bytes()[:8192]
        return b"\x00" in chunk
    except (OSError, PermissionError):
        return True


try:
    _GIT_TIMEOUT = int(os.environ.get("CRG_GIT_TIMEOUT", "30"))
except ValueError:
    _GIT_TIMEOUT = 30


def get_changed_files(repo_root: Path, base: str = "HEAD~1") -> list[str]:
    """Get list of changed files via git diff."""
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", base],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
        )
        if result.returncode != 0:
            # Fallback: try diff against empty tree (initial commit)
            result = subprocess.run(
                ["git", "diff", "--name-only", "--cached"],
                capture_output=True,
                text=True,
                cwd=str(repo_root),
                timeout=_GIT_TIMEOUT,
            )
        files = [f.strip() for f in result.stdout.splitlines() if f.strip()]
        return files
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_staged_and_unstaged(repo_root: Path) -> list[str]:
    """Get all modified files (staged + unstaged + untracked)."""
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
        )
        files = []
        for line in result.stdout.splitlines():
            if len(line) > 3:
                entry = line[3:].strip()
                # Handle renamed files: "R  old -> new"
                if " -> " in entry:
                    entry = entry.split(" -> ", 1)[1]
                files.append(entry)
        return files
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def get_all_tracked_files(repo_root: Path) -> list[str]:
    """Get all files tracked by git."""
    try:
        result = subprocess.run(
            ["git", "ls-files"],
            capture_output=True,
            text=True,
            cwd=str(repo_root),
            timeout=_GIT_TIMEOUT,
        )
        return [f.strip() for f in result.stdout.splitlines() if f.strip()]
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []


def collect_all_files(repo_root: Path) -> list[str]:
    """Collect all parseable files in the repo, respecting ignore patterns."""
    ignore_patterns = _load_ignore_patterns(repo_root)
    parser = CodeParser()
    files = []

    # Prefer git ls-files for tracked files
    tracked = get_all_tracked_files(repo_root)
    if tracked:
        candidates = tracked
    else:
        # Fallback: walk directory
        candidates = [
            str(p.relative_to(repo_root))
            for p in repo_root.rglob("*")
            if p.is_file()
        ]

    for rel_path in candidates:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        full_path = repo_root / rel_path
        if not full_path.is_file():
            continue
        if full_path.is_symlink():
            continue
        if parser.detect_language(full_path) is None:
            continue
        if _is_binary(full_path):
            continue
        files.append(rel_path)

    return files


def find_dependents(store: GraphStore, file_path: str) -> list[str]:
    """Find files that import from or depend on the given file.

    Looks at IMPORTS_FROM edges where target matches the file path.
    """
    dependents = set()
    # Find edges where someone imports from this file
    edges = store.get_edges_by_target(file_path)
    for e in edges:
        if e.kind == "IMPORTS_FROM":
            # The source is a file path (for IMPORTS_FROM edges)
            dependents.add(e.file_path)

    # Also check for DEPENDS_ON edges
    nodes = store.get_nodes_by_file(file_path)
    for node in nodes:
        for e in store.get_edges_by_target(node.qualified_name):
            if e.kind in ("CALLS", "IMPORTS_FROM", "INHERITS", "IMPLEMENTS"):
                dependents.add(e.file_path)

    dependents.discard(file_path)
    return list(dependents)


def full_build(repo_root: Path, store: GraphStore) -> dict:
    """Full rebuild of the entire graph."""
    parser = CodeParser()
    files = collect_all_files(repo_root)

    # Purge stale data from files no longer on disk
    existing_files = set(store.get_all_files())
    current_abs = {str(repo_root / f) for f in files}
    for stale in existing_files - current_abs:
        store.remove_file_data(stale)

    total_nodes = 0
    total_edges = 0
    errors = []
    file_count = len(files)

    for i, rel_path in enumerate(files, 1):
        full_path = repo_root / rel_path
        try:
            source = full_path.read_bytes()
            fhash = hashlib.sha256(source).hexdigest()
            nodes, edges = parser.parse_bytes(full_path, source)
            store.store_file_nodes_edges(str(full_path), nodes, edges, fhash)
            total_nodes += len(nodes)
            total_edges += len(edges)
        except (OSError, PermissionError) as e:
            errors.append({"file": rel_path, "error": str(e)})
        except Exception as e:
            logger.warning("Error parsing %s: %s", rel_path, e)
            errors.append({"file": rel_path, "error": str(e)})
        if i % 50 == 0 or i == file_count:
            logger.info("Progress: %d/%d files parsed", i, file_count)

    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "full")
    head = get_current_head(repo_root)
    if head:
        store.set_metadata("last_synced_commit", head)
    store.commit()

    return {
        "files_parsed": len(files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "errors": errors,
    }


def incremental_update(
    repo_root: Path,
    store: GraphStore,
    base: str = "HEAD~1",
    changed_files: list[str] | None = None,
) -> dict:
    """Incremental update: re-parse changed + dependent files only."""
    parser = CodeParser()
    ignore_patterns = _load_ignore_patterns(repo_root)

    # Determine changed files
    if changed_files is None:
        changed_files = get_changed_files(repo_root, base)

    if not changed_files:
        return {
            "files_updated": 0,
            "total_nodes": 0,
            "total_edges": 0,
            "changed_files": [],
            "dependent_files": [],
        }

    # Find dependent files (files that import from changed files)
    dependent_files: set[str] = set()
    for rel_path in changed_files:
        full_path = str(repo_root / rel_path)
        deps = find_dependents(store, full_path)
        for d in deps:
            # Convert back to relative path if needed
            try:
                dependent_files.add(str(Path(d).relative_to(repo_root)))
            except ValueError:
                dependent_files.add(d)

    # Combine changed + dependent
    all_files = set(changed_files) | dependent_files

    total_nodes = 0
    total_edges = 0
    errors = []

    for rel_path in all_files:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        abs_path = repo_root / rel_path
        if not abs_path.is_file():
            # File was deleted
            store.remove_file_data(str(abs_path))
            continue
        if parser.detect_language(abs_path) is None:
            continue

        try:
            source = abs_path.read_bytes()
            fhash = hashlib.sha256(source).hexdigest()
            # Check if file actually changed (compare against stored file_hash column)
            existing_nodes = store.get_nodes_by_file(str(abs_path))
            if existing_nodes and existing_nodes[0].file_hash == fhash:
                # Skip unchanged files (hash match)
                continue

            nodes, edges = parser.parse_bytes(abs_path, source)
            store.store_file_nodes_edges(str(abs_path), nodes, edges, fhash)
            total_nodes += len(nodes)
            total_edges += len(edges)
        except (OSError, PermissionError) as e:
            errors.append({"file": rel_path, "error": str(e)})
        except Exception as e:
            logger.warning("Error parsing %s: %s", rel_path, e)
            errors.append({"file": rel_path, "error": str(e)})

    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "incremental")
    head = get_current_head(repo_root)
    if head:
        store.set_metadata("last_synced_commit", head)
    store.commit()

    return {
        "files_updated": len(all_files),
        "total_nodes": total_nodes,
        "total_edges": total_edges,
        "changed_files": list(changed_files),
        "dependent_files": list(dependent_files),
        "errors": errors,
    }


# ---------------------------------------------------------------------------
# Git-aware sync
# ---------------------------------------------------------------------------


def get_current_head(repo_root: Path) -> str | None:
    """Get the current HEAD commit hash."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True, text=True,
            cwd=str(repo_root), timeout=_GIT_TIMEOUT,
        )
        return result.stdout.strip() if result.returncode == 0 else None
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None


def _get_git_diff_files(repo_root: Path, old_ref: str, new_ref: str) -> dict[str, list[str]]:
    """Get files changed between two git refs, categorized by status.

    Returns dict with keys: added, modified, deleted.
    """
    try:
        result = subprocess.run(
            ["git", "diff", "--name-status", f"{old_ref}..{new_ref}"],
            capture_output=True, text=True,
            cwd=str(repo_root), timeout=_GIT_TIMEOUT,
        )
        if result.returncode != 0:
            return {"added": [], "modified": [], "deleted": [], "error": "diff failed"}
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return {"added": [], "modified": [], "deleted": [], "error": "git unavailable"}

    added, modified, deleted = [], [], []
    for line in result.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        status = parts[0].strip()
        if status.startswith("R") or status.startswith("C"):
            # Rename/Copy: R100\told_path\tnew_path — track new path as modified, old as deleted
            if len(parts) >= 3:
                deleted.append(parts[1].strip())
                modified.append(parts[2].strip())
            else:
                modified.append(parts[1].strip())
        elif status.startswith("A"):
            added.append(parts[1].strip())
        elif status.startswith("D"):
            deleted.append(parts[1].strip())
        elif status.startswith(("M", "T")):
            modified.append(parts[1].strip())
    return {"added": added, "modified": modified, "deleted": deleted}


def _find_untracked_files(repo_root: Path, store: GraphStore, all_files: list[str]) -> list[str]:
    """Find files on disk that exist but are not in the graph (never synced)."""
    graph_files = set(store.get_all_files())
    untracked = []
    for rel_path in all_files:
        abs_path = str(repo_root / rel_path)
        if abs_path not in graph_files:
            untracked.append(rel_path)
    return untracked


def sync_with_git(repo_root: Path, store: GraphStore) -> dict:
    """Sync graph with git state by diffing last_synced_commit against HEAD.

    Detects files changed via git pull/checkout/merge and updates the graph.
    """
    parser = CodeParser()
    ignore_patterns = _load_ignore_patterns(repo_root)

    current_head = get_current_head(repo_root)
    if not current_head:
        return {"status": "skip", "reason": "not a git repository or git unavailable"}

    last_synced = store.get_metadata("last_synced_commit")

    # First-time sync: no stored commit
    if not last_synced:
        all_files = collect_all_files(repo_root)
        untracked = _find_untracked_files(repo_root, store, all_files)
        if not untracked:
            store.set_metadata("last_synced_commit", current_head)
            store.commit()
            return {"status": "ok", "reason": "first sync — graph already covers all files",
                    "synced_commit": current_head, "files_synced": 0}
        # Parse untracked files
        total_nodes, total_edges, errors = 0, 0, []
        for rel_path in untracked:
            if _should_ignore(rel_path, ignore_patterns):
                continue
            abs_path = repo_root / rel_path
            if not abs_path.is_file() or parser.detect_language(abs_path) is None:
                continue
            try:
                source = abs_path.read_bytes()
                fhash = hashlib.sha256(source).hexdigest()
                nodes, edges = parser.parse_bytes(abs_path, source)
                store.store_file_nodes_edges(str(abs_path), nodes, edges, fhash)
                total_nodes += len(nodes)
                total_edges += len(edges)
            except Exception as e:
                errors.append({"file": rel_path, "error": str(e)})
        store.set_metadata("last_synced_commit", current_head)
        store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
        store.commit()
        return {"status": "ok", "reason": "first sync — added missing files",
                "synced_commit": current_head, "files_synced": len(untracked),
                "total_nodes": total_nodes, "total_edges": total_edges, "errors": errors}

    # Same commit — already synced
    if last_synced == current_head:
        return {"status": "ok", "reason": "up_to_date", "synced_commit": current_head,
                "files_synced": 0}

    # Different commit — diff and sync
    diff = _get_git_diff_files(repo_root, last_synced, current_head)
    if "error" in diff:
        # Unreachable commit (rebase/force-push) — fall back to full rebuild
        logger.warning("Git diff failed (%s), falling back to full rebuild", diff["error"])
        result = full_build(repo_root, store)
        store.set_metadata("last_synced_commit", current_head)
        store.commit()
        return {"status": "ok", "reason": "full_rebuild_fallback",
                "synced_commit": current_head, **result}

    all_changed = diff["added"] + diff["modified"]
    total_nodes, total_edges, errors = 0, 0, []

    # Remove deleted files from graph
    for rel_path in diff["deleted"]:
        abs_path = str(repo_root / rel_path)
        store.remove_file_data(abs_path)

    # Find dependent files (files that import from changed files)
    dependent_files: set[str] = set()
    for rel_path in all_changed:
        full_path = str(repo_root / rel_path)
        deps = find_dependents(store, full_path)
        for d in deps:
            try:
                dependent_files.add(str(Path(d).relative_to(repo_root)))
            except ValueError:
                dependent_files.add(d)
    # Combine changed + dependent, excluding already-deleted
    all_to_parse = set(all_changed) | dependent_files

    # Parse changed/added/dependent files
    for rel_path in all_to_parse:
        if _should_ignore(rel_path, ignore_patterns):
            continue
        abs_path = repo_root / rel_path
        if not abs_path.is_file():
            continue
        if parser.detect_language(abs_path) is None:
            continue
        try:
            source = abs_path.read_bytes()
            fhash = hashlib.sha256(source).hexdigest()
            # Hash-based skip — don't re-parse if content unchanged
            existing = store.get_nodes_by_file(str(abs_path))
            if existing and existing[0].file_hash == fhash:
                continue
            nodes, edges = parser.parse_bytes(abs_path, source)
            store.store_file_nodes_edges(str(abs_path), nodes, edges, fhash)
            total_nodes += len(nodes)
            total_edges += len(edges)
        except Exception as e:
            errors.append({"file": rel_path, "error": str(e)})

    store.set_metadata("last_synced_commit", current_head)
    store.set_metadata("last_updated", time.strftime("%Y-%m-%dT%H:%M:%S"))
    store.set_metadata("last_build_type", "sync")
    store.commit()

    files_synced = len(all_changed) + len(diff["deleted"])
    return {
        "status": "ok", "reason": "synced",
        "synced_commit": current_head, "previous_commit": last_synced,
        "files_synced": files_synced,
        "added": len(diff["added"]), "modified": len(diff["modified"]),
        "deleted": len(diff["deleted"]),
        "total_nodes": total_nodes, "total_edges": total_edges,
        "errors": errors,
    }


# ---------------------------------------------------------------------------
# Watch mode
# ---------------------------------------------------------------------------


_DEBOUNCE_SECONDS = 0.3


try:
    from watchdog.events import FileSystemEventHandler as _BaseHandler
except ImportError:
    _BaseHandler = object


class _GraphUpdateHandler(_BaseHandler):
    """FileSystemEventHandler for graph auto-updates with debounce."""

    def __init__(self, repo_root: Path, store: GraphStore,
                 parser: CodeParser, ignore_patterns: list):
        self._repo_root = repo_root
        self._store = store
        self._parser = parser
        self._ignore_patterns = ignore_patterns
        self._pending: set[str] = set()
        self._lock: "threading.Lock | None" = None
        self._timer = None

    def _ensure_lock(self):
        if self._lock is None:
            import threading
            self._lock = threading.Lock()

    def _should_handle(self, path: str) -> bool:
        if Path(path).is_symlink():
            return False
        try:
            rel = str(Path(path).relative_to(self._repo_root))
        except ValueError:
            return False
        if _should_ignore(rel, self._ignore_patterns):
            return False
        if self._parser.detect_language(Path(path)) is None:
            return False
        return True

    def on_modified(self, event):
        if event.is_directory:
            return
        if self._should_handle(event.src_path):
            self._schedule(event.src_path)

    def on_created(self, event):
        if event.is_directory:
            return
        if self._should_handle(event.src_path):
            self._schedule(event.src_path)

    def on_deleted(self, event):
        if event.is_directory:
            return
        try:
            rel = str(Path(event.src_path).relative_to(self._repo_root))
        except ValueError:
            return
        if _should_ignore(rel, self._ignore_patterns):
            return
        self._store.remove_file_data(event.src_path)
        self._store.commit()
        logger.info("Removed: %s", rel)

    def _schedule(self, abs_path: str):
        import threading
        self._ensure_lock()
        with self._lock:
            self._pending.add(abs_path)
            if self._timer is not None:
                self._timer.cancel()
            self._timer = threading.Timer(_DEBOUNCE_SECONDS, self._flush)
            self._timer.start()

    def _flush(self):
        self._ensure_lock()
        with self._lock:
            paths = list(self._pending)
            self._pending.clear()
            self._timer = None
        for abs_path in paths:
            self._update_file(abs_path)

    def _update_file(self, abs_path: str):
        path = Path(abs_path)
        if not path.is_file() or path.is_symlink() or _is_binary(path):
            return
        try:
            source = path.read_bytes()
            fhash = hashlib.sha256(source).hexdigest()
            nodes, edges = self._parser.parse_bytes(path, source)
            self._store.store_file_nodes_edges(abs_path, nodes, edges, fhash)
            self._store.set_metadata(
                "last_updated", time.strftime("%Y-%m-%dT%H:%M:%S")
            )
            self._store.commit()
            rel = str(path.relative_to(self._repo_root))
            logger.info("Updated: %s (%d nodes, %d edges)", rel, len(nodes), len(edges))
        except Exception as e:
            logger.error("Error updating %s: %s", abs_path, e)


def watch(repo_root: Path, store: GraphStore) -> None:
    """Watch for file changes and auto-update the graph."""
    from watchdog.observers import Observer

    parser = CodeParser()
    ignore_patterns = _load_ignore_patterns(repo_root)
    handler = _GraphUpdateHandler(repo_root, store, parser, ignore_patterns)

    observer = Observer()
    observer.schedule(handler, str(repo_root), recursive=True)
    observer.start()

    logger.info("Watching %s for changes... (Ctrl+C to stop)", repo_root)
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
    logger.info("Watch stopped.")


