id: pat-260126-1643-uers28
category: general
type: preference
trigger:
  keywords: ["type", "annotations", "functions"]
  file_patterns: []
  context: add type annotations to all functions
content:
  wrong:

  right:

  rationale: add type annotations to all functions
metadata:
  source: explicit-teaching
  confidence: 1
  first_seen: 2026-01-26
  last_confirmed: 2026-02-24
  occurrences: 40
  confirmations: 39
  conflicts: 0
  related_files: []
tags: ["general", "type", "annotations", "functions"]