#!/usr/bin/env python3
"""
sweep-plan-whyreview-to-planreview.py

Transform every `plan -> why-review` adjacency in workflow sequences:
  - if the step AFTER why-review is already `plan-review`  -> DROP the why-review
    (dedup; plan-review already follows -> `plan -> plan-review`)
  - otherwise                                              -> REPLACE why-review
    with `plan-review` (`plan -> why-review -> X` => `plan -> plan-review -> X`)

End-state invariant: the step immediately after `plan` is `plan-review`.

Targets (canonical sources only; mirrors regenerated by codex sync afterwards):
  - .claude/workflows.json              (sequence arrays, line-based edit)
  - .claude/skills/workflow-*/SKILL.md  (step-chain lines + position tables)

Position tables: recomputed to literal 1-indexed positions. greenfield-init's
plan-review rows change OCCURRENCE COUNT (3->4) and are hand-fixed separately;
this script's recompute is skipped for greenfield-init (see --skip-postbl).

Usage:
  python sweep-plan-whyreview-to-planreview.py --dry-run
  python sweep-plan-whyreview-to-planreview.py --apply
"""
import argparse
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Files whose position tables are hand-fixed (count changes); skip auto-recompute.
POSTBL_SKIP = {"workflow-greenfield-init"}


def base_step(token):
    t = token.strip().strip(",").strip().strip('"').strip()
    if t.startswith("/") or t.startswith("$"):
        t = t[1:]
    t = re.sub(r"\s*\[.*?\]\s*$", "", t).strip()
    return t


# --------------------------------------------------------------------------- #
# workflows.json — line-based
# --------------------------------------------------------------------------- #
SEQ_ELEM_RE = re.compile(r'^(\s*)"([a-z0-9][a-z0-9 _\-\[\]=]*)"(,?)\s*$')


def _elem_base(line):
    m = SEQ_ELEM_RE.match(line)
    if not m:
        return None
    return base_step('"' + m.group(2) + '"')


def sweep_workflows_json(path, report):
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    out = []
    prev_base = None
    dropped = replaced = 0
    n = len(lines)
    for idx, ln in enumerate(lines):
        cur = _elem_base(ln)
        if cur is not None:
            if cur == "why-review" and prev_base == "plan":
                nxt_base = _elem_base(lines[idx + 1]) if idx + 1 < n else None
                if nxt_base == "plan-review":
                    report.append("  [json] dedup plan->why-review->plan-review")
                    dropped += 1
                    # keep prev_base == 'plan'
                    continue
                else:
                    out.append(ln.replace("why-review", "plan-review"))
                    report.append(f"  [json] replace plan->why-review->{nxt_base}")
                    replaced += 1
                    prev_base = "plan-review"
                    continue
            out.append(ln)
            prev_base = cur
        else:
            out.append(ln)
            prev_base = None
    return "".join(out), dropped, replaced


# --------------------------------------------------------------------------- #
# markdown step chains
# --------------------------------------------------------------------------- #
def sweep_step_chain(line):
    for sep in (" → ", " -> "):
        if sep in line and "why-review" in line:
            mstart = re.search(r"[/$][a-z]", line)
            if not mstart:
                return line, 0, 0
            prefix = line[: mstart.start()]
            chain = line[mstart.start():]
            tokens = chain.split(sep)
            stepish = [t for t in tokens if re.match(r"^\s*[/$][a-z]", t)]
            if len(stepish) < 3:
                return line, 0, 0
            new = []
            prev = None
            dropped = replaced = 0
            i = 0
            while i < len(tokens):
                t = tokens[i]
                b = base_step(t)
                if b == "why-review" and prev == "plan":
                    nb = base_step(tokens[i + 1]) if i + 1 < len(tokens) else None
                    if nb == "plan-review":
                        dropped += 1
                        i += 1
                        continue  # drop; prev stays 'plan'
                    else:
                        new.append(t.replace("why-review", "plan-review"))
                        prev = "plan-review"
                        replaced += 1
                        i += 1
                        continue
                new.append(t)
                prev = b
                i += 1
            if dropped or replaced:
                return prefix + sep.join(new), dropped, replaced
            return line, 0, 0
    return line, 0, 0


# --------------------------------------------------------------------------- #
# position tables
# --------------------------------------------------------------------------- #
POS_ROW_RE = re.compile(
    r"^(?P<head>\|\s*`[/$]?(?P<step>[a-z0-9\-]+)`\s*\|\s*)"
    r"(?P<occ>\d+)(?P<occsfx>st|nd|rd|th)"
    r"(?P<mid>\s*\(pos\s*)(?P<pos>\d+)(?P<rest>\).*)$"
)


def primary_steps_tokens(text):
    for line in text.splitlines():
        if ("why-review" in line or "/scout" in line or "$scout" in line or "/idea" in line) and (
            " → " in line or " -> " in line
        ):
            mstart = re.search(r"[/$][a-z]", line)
            if not mstart:
                continue
            sep = " → " if " → " in line else " -> "
            chain = line[mstart.start():]
            toks = [base_step(t) for t in chain.split(sep) if re.match(r"^\s*[/$][a-z]", t)]
            if len(toks) >= 3:
                return toks
    return None


def recompute_position_tables(text, report, fname):
    toks = primary_steps_tokens(text)
    if not toks:
        return text, 0
    positions = {}
    for i, t in enumerate(toks, start=1):
        positions.setdefault(t, []).append(i)
    out_lines = []
    changed = 0
    for line in text.splitlines(keepends=True):
        m = POS_ROW_RE.match(line.rstrip("\n"))
        if m:
            step = m.group("step")
            occ = int(m.group("occ"))
            plist = positions.get(step, [])
            if 1 <= occ <= len(plist):
                newpos = plist[occ - 1]
                oldpos = int(m.group("pos"))
                if newpos != oldpos:
                    nl = (m.group("head") + str(occ) + m.group("occsfx")
                          + m.group("mid") + str(newpos) + m.group("rest"))
                    if line.endswith("\n"):
                        nl += "\n"
                    out_lines.append(nl)
                    report.append(f"  [postbl:{fname}] {step} {occ}: pos {oldpos}->{newpos}")
                    changed += 1
                    continue
        out_lines.append(line)
    return "".join(out_lines), changed


def sweep_skill_file(path, report):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    lines = text.splitlines(keepends=True)
    new_lines = []
    dropped = replaced = 0
    fname = os.path.basename(os.path.dirname(path))
    for ln in lines:
        nl, d, r = sweep_step_chain(ln.rstrip("\n"))
        if d or r:
            dropped += d
            replaced += r
            new_lines.append(nl + ("\n" if ln.endswith("\n") else ""))
            report.append(f"  [md] {fname}: -{d} dedup / +{r} replace")
        else:
            new_lines.append(ln)
    text2 = "".join(new_lines)
    if fname not in POSTBL_SKIP:
        text2, _ = recompute_position_tables(text2, report, fname)
    else:
        report.append(f"  [postbl:{fname}] SKIPPED (hand-fixed: plan-review count change)")
    return text2, dropped, replaced


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    apply = args.apply and not args.dry_run

    report = []
    td = tr = 0

    wf = os.path.join(ROOT, ".claude", "workflows.json")
    new_wf, d, r = sweep_workflows_json(wf, report)
    td += d
    tr += r
    if apply and (d or r):
        with open(wf, "w", encoding="utf-8", newline="") as f:
            f.write(new_wf)

    for path in sorted(glob.glob(os.path.join(ROOT, ".claude", "skills", "workflow-*", "SKILL.md"))):
        new_txt, d, r = sweep_skill_file(path, report)
        td += d
        tr += r
        with open(path, encoding="utf-8") as f:
            cur = f.read()
        if apply and new_txt != cur:
            with open(path, "w", encoding="utf-8", newline="") as f:
                f.write(new_txt)

    mode = "APPLIED" if apply else "DRY-RUN"
    print(f"=== {mode}: {td} dedup-drops + {tr} replacements ===")
    for r in report:
        print(r)


if __name__ == "__main__":
    main()
