#!/usr/bin/env python3
"""
sweep-redundant-why-review.py

Remove redundant `why-review` workflow steps that immediately follow a REVIEW
skill step.

Rationale (note the two DISTINCT mechanisms — they are not the same scope):
  1. Internal gate: every review skill (except why-review itself) self-invokes
     `/why-review --validate-findings` as a Findings Validation Gate. That gate
     is TERMINAL and validates only the REVIEW SKILL'S OWN findings (correct /
     proof-backed / reasonable), NOT the underlying artifact's design rationale.
  2. Retained rationale gate: each affected workflow still keeps >=1 standalone
     full `why-review` later in its sequence (verified), which performs the
     adversarial design-rationale review (alternatives, pre-mortem, etc.).

A standalone `why-review` placed *immediately after* a review skill is therefore
redundant with the retained full rationale gate (the artifact's rationale was
already, or is still, challenged elsewhere) — it is NOT made redundant by the
internal validate-findings gate, which covers a different scope. Net rationale
coverage is preserved; only the back-to-back duplicate is dropped.

Targets (canonical sources only; .agents/ + .codex are regenerated by
the codex sync afterwards):
  - .claude/workflows.json          (sequence arrays, line-based edit)
  - .claude/skills/workflow-*/SKILL.md  (step-chain lines + position tables)

Usage:
  python sweep-redundant-why-review.py --dry-run
  python sweep-redundant-why-review.py --apply
"""
import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Review skills that embed the why-review findings-validation gate internally.
# review-changes is intentionally excluded: the parent review-changes workflow
# keeps an external why-review gate immediately after its first step.
# (Verified via grep for validate-findings / double-round-trip-review / Findings
#  Validation Gate across .claude/skills/*. why-review itself is excluded.)
REVIEW_SKILLS = {
    "review-architecture", "review-ui", "review-domain-entities",
    "review-artifact", "plan-review",
    "knowledge-review", "integration-test-review",
    "code-review", "production-readiness-review", "security-review", "performance",
}


def base_step(token):
    """Strip prefix (/ or $), arg suffix ([direction=sync]), whitespace/quotes."""
    t = token.strip().strip(",").strip().strip('"').strip()
    if t.startswith("/") or t.startswith("$"):
        t = t[1:]
    t = re.sub(r"\s*\[.*?\]\s*$", "", t).strip()
    return t


# --------------------------------------------------------------------------- #
# workflows.json — line-based removal inside sequence arrays
# --------------------------------------------------------------------------- #
SEQ_ELEM_RE = re.compile(r'^(\s*)"([a-z0-9][a-z0-9 _\-\[\]=]*)"(,?)\s*$')


def sweep_workflows_json(path, report):
    with open(path, encoding="utf-8") as f:
        lines = f.readlines()
    out = []
    prev_step = None  # base name of previous sequence element line, else None
    removed = 0
    for ln in lines:
        m = SEQ_ELEM_RE.match(ln)
        if m:
            step = base_step('"' + m.group(2) + '"')
            if step == "why-review" and prev_step in REVIEW_SKILLS:
                report.append(f"  [json] drop why-review after {prev_step}")
                removed += 1
                # do not emit; keep prev_step so a (hypothetical) chained
                # why-review,why-review after a review skill also collapses
                continue
            out.append(ln)
            prev_step = step
        else:
            out.append(ln)
            prev_step = None
    return "".join(out), removed


# --------------------------------------------------------------------------- #
# workflow skill markdown — step-chain lines
# --------------------------------------------------------------------------- #
def sweep_step_chain(line):
    """Return (new_line, n_removed) for a single markdown step-chain line."""
    for sep in (" → ", " -> "):
        if sep in line and ("why-review" in line):
            # split off any leading label like "**Steps:** "
            # find the start of the chain (first /token or $token)
            mstart = re.search(r"[/$][a-z]", line)
            if not mstart:
                return line, 0
            prefix = line[: mstart.start()]
            chain = line[mstart.start():]
            # trailing content after chain (rare) — keep tokens intact by split
            tokens = chain.split(sep)
            # Validate this really is a step chain (>=3 tokens, all look like steps)
            stepish = [t for t in tokens if re.match(r"^\s*[/$][a-z]", t)]
            if len(stepish) < 3:
                return line, 0
            new_tokens = []
            prev = None
            removed = 0
            for t in tokens:
                b = base_step(t)
                if b == "why-review" and prev in REVIEW_SKILLS:
                    removed += 1
                    # keep prev unchanged
                    continue
                new_tokens.append(t)
                prev = b
            if removed:
                return prefix + sep.join(new_tokens), removed
            return line, 0
    return line, 0


# --------------------------------------------------------------------------- #
# position tables: | `/step` | Nth (pos X) | desc |
# --------------------------------------------------------------------------- #
POS_ROW_RE = re.compile(
    r"^(?P<head>\|\s*`[/$]?(?P<step>[a-z0-9\-]+)`\s*\|\s*)"
    r"(?P<occ>\d+)(?P<occsfx>st|nd|rd|th)"
    r"(?P<mid>\s*\(pos\s*)(?P<pos>\d+)(?P<rest>\).*)$"
)


def primary_steps_tokens(text):
    """Return base-step list from the first markdown step-chain line found."""
    for line in text.splitlines():
        if ("why-review" in line or "/scout" in line or "$scout" in line) and (
            " → " in line or " -> " in line
        ):
            mstart = re.search(r"[/$][a-z]", line)
            if not mstart:
                continue
            sep = " → " if " → " in line else " -> "
            chain = line[mstart.start():]
            toks = [base_step(t) for t in chain.split(sep) if re.match(r"^\s*[/$][a-z]", t)]
            if len(toks) >= 3:
                return toks
    return None


def recompute_position_tables(text, report, fname):
    toks = primary_steps_tokens(text)
    if not toks:
        return text, 0
    # positions per step (1-indexed, literal over full sequence)
    positions = {}
    for i, t in enumerate(toks, start=1):
        positions.setdefault(t, []).append(i)
    out_lines = []
    changed = 0
    for line in text.splitlines(keepends=True):
        m = POS_ROW_RE.match(line.rstrip("\n"))
        if m:
            step = m.group("step")
            occ = int(m.group("occ"))
            plist = positions.get(step, [])
            if 1 <= occ <= len(plist):
                newpos = plist[occ - 1]
                oldpos = int(m.group("pos"))
                if newpos != oldpos:
                    nl = (
                        m.group("head")
                        + str(occ)
                        + m.group("occsfx")
                        + m.group("mid")
                        + str(newpos)
                        + m.group("rest")
                    )
                    # preserve trailing newline
                    if line.endswith("\n"):
                        nl += "\n"
                    out_lines.append(nl)
                    report.append(f"  [postbl:{fname}] {step} {occ}: pos {oldpos}->{newpos}")
                    changed += 1
                    continue
        out_lines.append(line)
    return "".join(out_lines), changed


def sweep_skill_file(path, report):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    lines = text.splitlines(keepends=True)
    new_lines = []
    removed = 0
    for ln in lines:
        nl, r = sweep_step_chain(ln.rstrip("\n"))
        if r:
            removed += r
            new_lines.append(nl + ("\n" if ln.endswith("\n") else ""))
            report.append(f"  [md] {os.path.basename(os.path.dirname(path))}: -{r} why-review")
        else:
            new_lines.append(ln)
    text2 = "".join(new_lines)
    text2, _ = recompute_position_tables(text2, report, os.path.basename(os.path.dirname(path)))
    return text2, removed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    apply = args.apply and not args.dry_run

    report = []
    total = 0

    # 1) workflows.json
    wf = os.path.join(ROOT, ".claude", "workflows.json")
    new_wf, n = sweep_workflows_json(wf, report)
    total += n
    if apply and n:
        with open(wf, "w", encoding="utf-8", newline="") as f:
            f.write(new_wf)

    # 2) workflow skill files (.claude canonical)
    for path in sorted(glob.glob(os.path.join(ROOT, ".claude", "skills", "workflow-*", "SKILL.md"))):
        new_txt, n = sweep_skill_file(path, report)
        if n:
            total += n
        with open(path, encoding="utf-8") as f:
            cur = f.read()
        if apply and new_txt != cur:
            with open(path, "w", encoding="utf-8", newline="") as f:
                f.write(new_txt)

    mode = "APPLIED" if apply else "DRY-RUN"
    print(f"=== {mode}: {total} why-review removals + position-table updates ===")
    for r in report:
        print(r)


if __name__ == "__main__":
    main()
