id: pat-260126-1643-aatzym
category: frontend
type: preference
trigger:
  keywords: ["always", "semicolons", "typescript"]
  file_patterns: []
  context: always use semicolons in TypeScript
content:
  wrong:

  right: semicolons in TypeScript
  rationale: always use semicolons in TypeScript
metadata:
  source: explicit-teaching
  confidence: 1
  first_seen: 2026-01-26
  last_confirmed: 2026-02-24
  occurrences: 40
  confirmations: 39
  conflicts: 0
  related_files: []
tags: ["frontend", "always", "semicolons", "typescript"]