id: pat-260126-1643-u4fgbv
category: frontend
type: preference
trigger:
  keywords: ["naming", "classes"]
  file_patterns: []
  context: use BEM naming for CSS classes
content:
  wrong:

  right:

  rationale: use BEM naming for CSS classes
metadata:
  source: explicit-teaching
  confidence: 1
  first_seen: 2026-01-26
  last_confirmed: 2026-02-24
  occurrences: 40
  confirmations: 39
  conflicts: 0
  related_files: []
tags: ["frontend", "naming", "classes"]