version: '3.4'

services:
  sql-data:
    image: ${REGISTRY:-duc01226}/easy-platform-example-app-fts-sql-data:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: fts-sqldata.Dockerfile

  mongo-data:
    image: mongo:4.2

  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine

  redis-cache:
    image: redis:6.2.5

  text-snippet-api:
    image: ${REGISTRY:-duc01226}/easy-platform-example-app-text-snippet-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/PlatformExampleApp.TextSnippet.Api/Dockerfile
    depends_on:
      - sql-data
      - mongo-data
      - rabbitmq
      - redis-cache

  text-snippet-webspa:
    image: ${REGISTRY:-duc01226}/easy-platform-example-app-text-snippet-webspa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: Web
      args:
        configuration: 'production'
      dockerfile: apps/text-snippet/Dockerfile
    depends_on:
      - text-snippet-api
